import logging

logger = logging.getLogger(__name__)


def generate_prescription_html(prescription_data):
    """Generate HTML content for a prescription PDF."""
    clinic_name = prescription_data.get("clinic_name", "CareDesk Clinic")
    doctor_name = prescription_data.get("doctor_name", "")
    patient_name = prescription_data.get("patient_name", "")
    patient_age = prescription_data.get("patient_age", "")
    patient_gender = prescription_data.get("patient_gender", "")
    diagnosis = prescription_data.get("diagnosis", "")
    medicines = prescription_data.get("medicines", [])
    advice = prescription_data.get("advice", "")
    follow_up_date = prescription_data.get("follow_up_date", "")
    date = prescription_data.get("date", "")

    medicines_rows = ""
    for i, med in enumerate(medicines, 1):
        medicines_rows += f"""
        <tr>
            <td style="padding:8px;border:1px solid #e2e8f0;">{i}</td>
            <td style="padding:8px;border:1px solid #e2e8f0;">{med.get('name','')}</td>
            <td style="padding:8px;border:1px solid #e2e8f0;">{med.get('dosage','')}</td>
            <td style="padding:8px;border:1px solid #e2e8f0;">{med.get('duration','')}</td>
            <td style="padding:8px;border:1px solid #e2e8f0;">{med.get('instructions','')}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Prescription</title></head>
<body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;">
  <div style="border-bottom:3px solid #0d9488;padding-bottom:16px;margin-bottom:20px;">
    <h1 style="color:#0d9488;margin:0;">{clinic_name}</h1>
    <p style="color:#64748b;margin:4px 0 0;">Digital Prescription</p>
  </div>
  <div style="display:flex;justify-content:space-between;margin-bottom:20px;">
    <div>
      <p><strong>Patient:</strong> {patient_name}</p>
      <p><strong>Age/Gender:</strong> {patient_age} / {patient_gender}</p>
    </div>
    <div style="text-align:right;">
      <p><strong>Doctor:</strong> Dr. {doctor_name}</p>
      <p><strong>Date:</strong> {date}</p>
    </div>
  </div>
  <div style="background:#f0fdfa;padding:12px;border-radius:8px;margin-bottom:20px;">
    <p style="margin:0;"><strong>Diagnosis:</strong> {diagnosis}</p>
  </div>
  <h3 style="color:#0d9488;">Rx - Medicines</h3>
  <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
    <thead>
      <tr style="background:#f1f5f9;">
        <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">#</th>
        <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Medicine</th>
        <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Dosage</th>
        <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Duration</th>
        <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Instructions</th>
      </tr>
    </thead>
    <tbody>{medicines_rows}</tbody>
  </table>
  {f'<div style="margin-bottom:16px;"><strong>Advice:</strong> {advice}</div>' if advice else ''}
  {f'<div style="margin-bottom:16px;"><strong>Follow-up Date:</strong> {follow_up_date}</div>' if follow_up_date else ''}
  <hr style="border:1px solid #e2e8f0;margin-top:40px;">
  <p style="color:#94a3b8;font-size:12px;text-align:center;">Generated by CareDesk — Smart Clinic Management System</p>
</body>
</html>"""
    return html


def generate_pdf(app, html_content):
    """
    Generate a PDF from HTML using Catalyst SmartBrowz.
    Returns PDF bytes or None on failure.
    """
    try:
        smart_browz = app.smart_browz()
        pdf_bytes = smart_browz.convert_to_pdf(html_content)
        logger.info("SmartBrowz PDF generated successfully")
        return pdf_bytes
    except Exception as e:
        logger.warning(f"SmartBrowz PDF generation failed: {e}")
        return None
